# Generated by Django 2.1.7 on 2019-10-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='platinum_member',
            field=models.BooleanField(default=False),
        ),
    ]
