# Generated by Django 2.1.7 on 2019-10-15 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0002_user_platinum_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gold_member',
        ),
        migrations.RemoveField(
            model_name='user',
            name='platinum_member',
        ),
    ]
