# Generated by Django 2.1.7 on 2019-09-21 18:03

import common.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlatBerat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nama_alat', models.CharField(blank=True, max_length=255, null=True)),
                ('satuan', models.CharField(blank=True, max_length=255, null=True)),
                ('merek', models.CharField(blank=True, max_length=255, null=True)),
                ('tahun_pembuatan', models.IntegerField(default=0)),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Alat Berat',
                'verbose_name_plural': 'Alat Berat',
                'db_table': 'alat_berat',
            },
        ),
        migrations.CreateModel(
            name='KabupatenKota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Kabupaten Kota',
                'verbose_name_plural': 'Kabupaten Kota',
                'db_table': 'kabupaten_kota',
            },
        ),
        migrations.CreateModel(
            name='Klasifikasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Klasifikasi',
                'verbose_name_plural': 'Klasifikasi',
                'db_table': 'klasifikasi',
            },
        ),
        migrations.CreateModel(
            name='Kualifikasi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Kualifikasi',
                'verbose_name_plural': 'Kualifikasi',
                'db_table': 'kualifikasi',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nama_material', models.CharField(blank=True, max_length=255, null=True)),
                ('satuan', models.CharField(blank=True, max_length=255, null=True)),
                ('merek', models.CharField(blank=True, max_length=255, null=True)),
                ('harga_per_satuan', models.DecimalField(decimal_places=4, default=0, max_digits=40)),
                ('keterangan', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Material',
                'db_table': 'material',
            },
        ),
        migrations.CreateModel(
            name='PengalamanKerja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uraian_pekerjaan', common.fields.BinaryTextField(blank=True, null=True)),
                ('pemberi_kerja', models.CharField(max_length=255)),
                ('tahun_pelaksanaan', models.DateField()),
                ('nilai_kontrak', models.DecimalField(decimal_places=4, max_digits=40)),
            ],
            options={
                'verbose_name': 'Pengalaman Kerja',
                'verbose_name_plural': 'Pengalaman Kerja',
                'db_table': 'pengalaman_kerja',
            },
        ),
        migrations.CreateModel(
            name='Profesi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Profesi',
                'verbose_name_plural': 'Profesi',
                'db_table': 'profesi',
            },
        ),
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Provinsi',
                'verbose_name_plural': 'Provinsi',
                'db_table': 'provinsi',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('bersedia_mengirim_ke_lokasi_pekerjaan', models.BooleanField(default=False)),
                ('nama', models.CharField(max_length=255)),
                ('no_telepon', models.IntegerField(default=0)),
                ('nama_perusahaan', models.CharField(max_length=255)),
                ('jabatan_di_perusahaan', models.CharField(max_length=255)),
                ('alamat_perusahaan', models.CharField(max_length=255)),
                ('sertifikat_badan_usaha', models.ImageField(blank=True, default=None, null=True, upload_to='docs/sertifikat_badan_usaha/%Y/%m/%D/')),
                ('siup_keahlian_khusus', models.ImageField(blank=True, default=None, null=True, upload_to='docs/siup_keahlian_khusus/%Y/%m/%D/')),
                ('pas_photo', models.ImageField(blank=True, default=None, null=True, upload_to='docs/pas_photo/%Y/%m/%D/')),
                ('selfie_dengan_identitas_diri', models.ImageField(blank=True, default=None, null=True, upload_to='docs/selfie_dengan_identitas_diri/%Y/%m/%D/')),
                ('masalah_yang_sering_dihadapi', common.fields.BinaryTextField(blank=True, null=True)),
                ('bantuan_yang_dibutuhkan', common.fields.BinaryTextField(blank=True, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=20, default=0, max_digits=50)),
                ('long', models.DecimalField(blank=True, decimal_places=20, default=0, max_digits=50)),
                ('sekolah_dasar', models.CharField(blank=True, max_length=255, null=True)),
                ('sekolah_menengah_pertama', models.CharField(blank=True, max_length=255, null=True)),
                ('sekolah_menengah_kejuruan', models.CharField(blank=True, max_length=255, null=True)),
                ('universitas', models.CharField(blank=True, max_length=255, null=True)),
                ('sertifikat_ketrampilan1', models.FileField(blank=True, default=None, null=True, upload_to='docs/sertifikat_ketrampilan/%Y/%m/%D/')),
                ('sertifikat_ketrampilan2', models.FileField(blank=True, default=None, null=True, upload_to='docs/sertifikat_ketrampilan/%Y/%m/%D/')),
                ('sertifikat_ketrampilan3', models.FileField(blank=True, default=None, null=True, upload_to='docs/sertifikat_ketrampilan/%Y/%m/%D/')),
                ('pengalaman_kerja1', models.CharField(blank=True, max_length=255, null=True)),
                ('pengalaman_kerja2', models.CharField(blank=True, max_length=255, null=True)),
                ('surat_keterangan_kerja1', models.FileField(blank=True, default=None, null=True, upload_to='docs/surat_keterangan_kerja/%Y/%m/%D/')),
                ('surat_keterangan_kerja2', models.FileField(blank=True, default=None, null=True, upload_to='docs/surat_keterangan_kerja/%Y/%m/%D/')),
                ('kabupaten_kota', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_info.KabupatenKota')),
                ('klasifikasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_info.Klasifikasi')),
                ('kualifikasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_info.Kualifikasi')),
                ('profesi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_info.Profesi')),
                ('provinsi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_info.Provinsi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Info',
                'verbose_name_plural': 'Users Info',
                'db_table': 'user_info',
            },
        ),
        migrations.AddField(
            model_name='pengalamankerja',
            name='user_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pengalaman_kerja', to='user_info.UserInfo'),
        ),
        migrations.AddField(
            model_name='material',
            name='user_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='material', to='user_info.UserInfo'),
        ),
        migrations.AddField(
            model_name='kualifikasi',
            name='profesi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_info.Profesi'),
        ),
        migrations.AddField(
            model_name='klasifikasi',
            name='profesi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user_info.Profesi'),
        ),
        migrations.AddField(
            model_name='alatberat',
            name='user_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='alat_berat', to='user_info.UserInfo'),
        ),
    ]
