# Generated by Django 2.1.7 on 2019-10-11 16:35

import django.db.models.deletion
from django.db import migrations, models

import common.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nama_produk', models.CharField(max_length=255)),
                ('nama_perusahaan', models.CharField(max_length=255)),
                ('jenis_member', models.CharField(max_length=255)),
                ('gambar', models.ImageField(blank=True, default=None, null=True, upload_to='docs/produk/%Y/%m/%D/')),
                ('deskripsi', common.fields.BinaryTextField()),
                ('kabupatenkota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_info.KabupatenKota')),
                ('klasifikasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_info.Klasifikasi')),
                ('kualifikasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_info.Kualifikasi')),
                ('perusahaan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_list', to='user_info.UserInfo')),
                ('provinsi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_info.Provinsi')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Product',
                'db_table': 'products',
            },
        ),
    ]
