# Generated by Django 2.1.7 on 2019-10-11 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keahlian',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
                ('profesi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='keahlian_list', to='user_info.Profesi')),
            ],
            options={
                'verbose_name': 'keahlian',
                'verbose_name_plural': 'keahlian',
                'db_table': 'keahlian',
            },
        ),
        migrations.AlterField(
            model_name='klasifikasi',
            name='profesi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='klasifikasi_list', to='user_info.Profesi'),
        ),
        migrations.AlterField(
            model_name='kualifikasi',
            name='profesi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='kualifikasi_list', to='user_info.Profesi'),
        ),
    ]
