# Generated by Django 2.1.7 on 2019-10-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0003_auto_20191011_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='logo_perusahaan',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='docs/logo_perusahaan/%Y/%m/%D/'),
        ),
    ]
