# Generated by Django 2.1.7 on 2019-10-11 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0004_userinfo_logo_perusahaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='kabupatenkota',
            name='provinsi',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kabupaten_list', to='user_info.Provinsi'),
        ),
    ]
