# Generated by Django 2.1.7 on 2019-10-11 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0005_kabupatenkota_provinsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kabupatenkota',
            name='provinsi',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='kabupaten_list', to='user_info.Provinsi'),
        ),
    ]
