# Generated by Django 2.1.7 on 2019-10-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0006_auto_20191011_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='no_telepon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
