# Generated by Django 2.1.7 on 2019-10-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0007_auto_20191011_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deskripsi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
