# Generated by Django 2.1.7 on 2019-10-11 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0008_auto_20191011_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengalamankerja',
            name='uraian_pekerjaan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='bantuan_yang_dibutuhkan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='masalah_yang_sering_dihadapi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
