# Generated by Django 2.1.7 on 2019-10-11 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0009_auto_20191011_2234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='jenis_member',
        ),
        migrations.RemoveField(
            model_name='product',
            name='kabupatenkota',
        ),
        migrations.RemoveField(
            model_name='product',
            name='klasifikasi',
        ),
        migrations.RemoveField(
            model_name='product',
            name='kualifikasi',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nama_perusahaan',
        ),
        migrations.RemoveField(
            model_name='product',
            name='provinsi',
        ),
    ]
