# Generated by Django 2.1.7 on 2019-10-15 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0011_auto_20191015_0710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lowongan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('posisi', models.CharField(max_length=255)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('berakhir_pada', models.DateField()),
            ],
            options={
                'verbose_name': 'Lowongan',
                'verbose_name_plural': 'Lowongan',
                'db_table': 'lowongan',
            },
        ),
        migrations.AddField(
            model_name='userinfo',
            name='kantor_cabang',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='rating',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lowongan',
            name='perusahaan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lowongan_list', to='user_info.UserInfo'),
        ),
    ]
