# Generated by Django 2.1.7 on 2019-10-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0013_auto_20191016_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalkontak',
            name='hp',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
