# Generated by Django 2.2.6 on 2019-10-17 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0013_auto_20191017_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoloker',
            name='perusahaan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loker_list', to='user_info.UserInfo'),
        ),
    ]
