# Generated by Django 2.2.6 on 2019-10-17 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0014_auto_20191017_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoloker',
            name='perusahaan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='loker_list', to='user_info.UserInfo'),
        ),
    ]
