# Generated by Django 2.2.6 on 2019-10-17 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0015_auto_20191017_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoloker',
            name='perusahaan',
        ),
    ]
