# Generated by Django 2.2.6 on 2019-10-17 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0016_remove_infoloker_perusahaan'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoloker',
            name='perusahaan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loker_list', to='user_info.UserInfo'),
        ),
    ]
