# Generated by Django 2.1.7 on 2019-10-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0017_product_gaji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='fasilitas',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gaji',
        ),
        migrations.RemoveField(
            model_name='product',
            name='keahlian',
        ),
        migrations.RemoveField(
            model_name='product',
            name='kualifikasi',
        ),
        migrations.AddField(
            model_name='lowongan',
            name='fasilitas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lowongan',
            name='gaji',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='lowongan',
            name='keahlian',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lowongan',
            name='kualifikasi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
