# Generated by Django 2.1.7 on 2019-10-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0019_carouselimage_event_news_pengadaan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('jabatan', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('perusahaan', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('isi', models.TextField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonial',
                'db_table': 'testimonial',
            },
        ),
    ]
