# Generated by Django 2.1.7 on 2019-10-18 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_info', '0017_infoloker_perusahaan'),
        ('user_info', '0020_testimonial'),
    ]

    operations = [
    ]
